### ISSUE TITLE
posun dat o metry

### ISSUE THREAD

**Issue by juhele** [ctu-osgeorel-proj/bp-pesek-2016#14]
zdravím,
zkusil jsem si nasimulovat krátkodobý výpadek GPS a smazal část dat v jedné linii. 
Pokud použiju posun o několik metrů, tak se mi "díra" způsobená "výpadkem" dat nezaplňuje, ale jakoby to teče přes ni.

Myslel jsem, že v tomto nastavení bere algoritmus v potaz vzdálenost, a že by mi měl body posunout na přímku i do oblasti s původně chybějícími daty.

nebo je to jinak?

díky

[lokalita1_data_pub-data_drop.zip](https://github.com/ctu-osgeorel-proj/bp-pesek-2016/files/215092/lokalita1_data_pub-data_drop.zip)

**Comment by pesekon2** [comment]
Zdravím, 

posun o metry funguje tak, že se mezi každými dvěma body vypočte trajektorie na elipsoidu a následně se dříve měřený z těchto bodů po této trajektorii posune o zadanou vzdálenost. 

K tomu samozřejmě dochází, i když se nachází v měření nějaká mezera. Ale ježto jde o posun o konstantní vzdálenost, v podstatě dojde k tomu, že se o tutéž vzdálenost posune i ona "díra". 

K žádnému zaplňování výpadků v posunu nedochází. V žádném z posunů. 
K tomu by asi bylo potřeba v pluginu generovat nové body, což plugin neumí; byl by problém také v tom, že by se např. nejdůležitější část, hodnota měření, jen odhadovala nějakou lineární interpolací. 

Pokud jsem úplně mimo, klidně svůj dotaz více specifikujte. 

Mockrát díky za test

**Comment by juhele** [comment]
OK, tak jsem si to vyzkoušel v Inkcape a máte pravdu, ta "díra" se samozřejmě posune taky. Ještě jsem si všiml, že někdy dochází k ujetí bodů v koncových smyčkách - smyčka se jakoby víc rozbalí ven, ačkoliv bych čekal, že se data jen posunou podél té trajektorie. Ukážu to zítra kolegovi, zda to nějak vadí.

![posun_bodu svg](https://cloud.githubusercontent.com/assets/1697788/14473824/3b0a3e6c-00fa-11e6-9dc8-db41f0b9ef9e.png)

**Comment by pesekon2** [comment]
O tom rozbalení ven vím. Je to způsobeno tím, že počítá trajektorii mezi dvěma nejbližšími body; pokud posun překračuje prostor mezi dvěma body, nepřepočítává se trajektorie na další bod. 

V podstatě bych i věděl, jak to udělat, ale: 
1) Bylo by to obrovsky náročné na paměť (při větším množství dat by trvala operace ohromnou dobu)
2) Nevím, zda to má cenu. Pokud vše chápu správně, posun o více než 1 bod nedává smysl, protože GPS zapisuje souřadnice na začátku nebo na konci měření, ale nikoli např. o 2 měření později. Je to tak? 

Ale jak říkám, kdyžtak jsem schopen tohle udělat, jen zatím pro to nevidím uplatnění a bojím se, že to bude náročnější na systém. Co na to říkal kolega?

**Comment by juhele** [comment]
Tak jsem to porovnal a ono bohužel k těm posunům mimo trasu letu dochází i při námi standardně používaném 3s posunu:

![leveling_posuny](https://cloud.githubusercontent.com/assets/1697788/14636036/755a2df0-0629-11e6-83be-5ad9def1694d.png)

Předpokládám, že algoritmus posunu bude stejný, takže k témuž dojde při posunu o vzdálenost.

**Comment by pesekon2** [comment]
Zkuste si prosím zesynchronizovat plugin. Právě jsem nahrál verzi, která by měla mít tenhle problém pro posun o vteřiny vyřešený. Docela se to podepsalo na přehlednosti kódu, ale to je uživateli asi šumafuk. Co jsem zkoušel, mělo by to být vyřešené. Moc díky za zpětnou vazbu. 
Posun o metry podobným způsobem vyřeším snad během dneška, nejpozději zítra. 

PS: Nemohl byste mi poslat nějaká vaše největší data, abychom ozkoušeli, jak rychle to funguje? Tohle vylepšení podstatně zvětšilo nároky na systém. S rozsáhlejšími daty, která mám k dispozici, jsem na počítači s nijak kvalitním výkonem při testování nikdy nepřekročil sedm sekund výpočtu (což je podle mě pořád tolerovatelné), ale nevím, nakolik mohou být data objemnější. 

Díky.

**Comment by landam** [comment]
@pesekon2 resenim by mohlo byt pouziti tridy Geod z pyproj (pokud ji bude mit uzivatel na systemu nainstalovanu), viz http://jswhit.github.io/pyproj/pyproj.Geod-class.html

**Comment by juhele** [comment]
@landam zmíněnou třídu je nutné instalovat separátně ručně, nebo to lze nějak "přibalit" aby se tím uživatel nemusel moc zabývat?

@pesekon2 OK, vyhrabu nějaká další data :-)

**Comment by landam** [comment]
@juhele knihovnu PyProj je potreba doinstalovat separatne, "nakopirovat" tridu rozhodne nestaci. Predtim by ale mely byt provedeny testy, zda to ma vubec smysl, viz https://github.com/ctu-osgeorel-proj/bp-pesek-2016/blob/master/test.py
@pesekon2 je v testech nejaky progres?

**Comment by juhele** [comment]
[lokalita3_unrealdata_pub.zip](https://github.com/ctu-osgeorel-proj/bp-pesek-2016/files/236916/lokalita3_unrealdata_pub.zip)

Zdravím, našel jsem nějaká další data, ale podle mne větší nemáme s ohledem na omezený dolet vrtulníku.

Nicméně, jak nad tím přemýšlím, tak asi pro mne nebude problém vyrobit data simulující např. trojásobek naší letové doby. Večer se na to doma mrknu a kdyžtak to sem přidám.

Jinak jsem přeinstaloval plugin a zkusil zatím posun o hodnoty a o metry a obojí nyní bez "ujetí" mimo trasu, takže super!!!

**Comment by juhele** [comment]
Tak jsem vyrobil pro otestování velký dataset
![lokalita3_unrealdata_pub_big_nahled](https://cloud.githubusercontent.com/assets/1697788/14834096/f636d386-0c02-11e6-9ee7-235ee08537c1.jpeg)

Data opět volně k dispozici:
[lokalita3_unrealdata_pub_big.zip](https://github.com/ctu-osgeorel-proj/bp-pesek-2016/files/237508/lokalita3_unrealdata_pub_big.zip)

Co jsem to zatím zkoušel, tak posun funguje plynule a bezproblémově - zkusím zítra na slabším notebooku. Ale každopádně z toho mám dobrý pocit.

**Comment by pesekon2** [comment]
Díky za data. Testy mi ukazují na lokalita3_unrealdata_pub_big v průměru 6.5 s výpočtů. 

Podle mě je to docela tolerovatelná doba. Implementace pyproj mi tedy zatím přijde jako nepodstatná - nevíme, zda opravdu dojde k zrychlení, a nejsem si jist, zda by takové zrychlení vyvážilo nárůst velikosti pluginu a potřebu dodatečné instalace pyproj. Nechal bych to kdyžtak na závěr BP, pokud zbyde čas. Co na to @landam ?

**Comment by landam** [comment]
@pesekon2 souhlasim.
