### ISSUE TITLE
reimplementace stylu

### ISSUE THREAD

**Issue by landam** [ctu-osgeorel-proj/bp-pesek-2016#16]
- bez preddefinovanych stylu, implementace jako pushbutton
- zmensit sirku okna

**Comment by landam** [comment]
Jaky ma smysl nasledujici kod?

```
+    if stylePath==0:
+        pass
+    else:
```

V konstruktoru tridy je take

```
self.stylePath=0
```

tady predpokladam, ze jste spise mel na mysli

```
self.stylePath=None
```

(opakuje se na vice mistech)
?

**Comment by landam** [comment]
Poznamky k UI:

![suro-leveling](https://cloud.githubusercontent.com/assets/5683186/14935737/9653378a-0edb-11e6-9dd6-3cf2a5af555e.png)

1) pod GNOME maji widgety v boxsizeru malou vysku
2) tlaticko 'No Style' navrhuji dat alespon do stejne radky jako 'Solve'

**Comment by pesekon2** [comment]
Asi by byl smysluplnější None. 

```
+    if stylePath==0:
+        pass
+    else:
```

Jde o to, že je-li v stylePath 0 (None), nemá dojít k nastylování vstupujících dat. Ale je fakt, že by se tahle větev měla úplně vynechat, stačí hodit větev s nastylováním do if. Jdu to napravit a mrknout se na UI.

**Comment by landam** [comment]
Ano,

```
if stylePath:
    ...
```

**Comment by landam** [comment]
UI vypada kompaktne i pod Gnone:

![suro1](https://cloud.githubusercontent.com/assets/5683186/14938385/d3cc8544-0f21-11e6-9943-19d7b10dce4c.png)
